config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
   # get "/some/route" => "some_devise_controller"
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    scope module: :public do
     post 'guest_sign_in', to: 'sessions#guest_sign_in'
    end
  end


  scope module: :public do

    #post 'guest_sign_in', to: 'sessions#guest_sign_in'

    post "rates/create"

    get "books/search"

    get "books/category_search"

    resource :customers, only: [:show]

    resources :books, except: [:new, :edit] do

      resources :posts, only: [:create, :destroy]

    end

  end



  # 管理者用
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    patch "/customers/:id/" => "customers#withdrawal", as: "withdrawal"
    resources :customers, only: [:show, :index, :update]
    resources :posts, only: [:show, :destroy]

  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true

  # emailとpasswordを生成
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      # SecureRandom.urlsafe_base64でランダムに64の文字数列を生成
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @books = Book.where(read_st: true,)
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end

  # 退会させるボタンを押したら動く
  def withdrawal
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    redirect_to admin_customers_path
  end


  private

  def customer_params
    params.require(:customer).permit(:name, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col center-block">
      <br> <br><h3>会員一覧</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.name, admin_customer_path(customer) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == false %>
              <p class="text-success">有効</p>
              <% else %>
              <p class="text-danger">退会</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col center-block">
      <br><h3>会員詳細</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted == false %>
              <span class="label label-primary">
              <p class="text-success">有効会員</p>
              </span>
              <% else %>
              <span class="label label-danger">
                <p class="text-danger">無効会員</p>
              </span>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <br><table class="table">
        <thead>
          <tr>
            <th>コメントした本</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |books| %>
          <% if @customer.id == books.customer_id %>
          <tr>
            <td><%= books.title %></td>
            <td><%= link_to "コメントを見る", admin_post_path(books.id) %></td>
          </tr>
          <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="text-center">
    <% if @customer.is_deleted == false %>
    <%= link_to "退会させる", admin_withdrawal_path, method: :patch, data: { confirm: '本当に退会させますか？' }, class: "btn btn-outline-danger" %>
    <% end %>
  </div>
</div>