config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
   # get "/some/route" => "some_devise_controller"
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    scope module: :public do
     post 'guest_sign_in', to: 'sessions#guest_sign_in'
    end
  end


  scope module: :public do

    #post 'guest_sign_in', to: 'sessions#guest_sign_in'

    post "rates/create"

    get "books/search"

    get "books/category_search"

    resource :customers, only: [:show]

    resources :books, except: [:new, :edit] do

      resources :posts, only: [:create, :destroy]

    end

  end



  # 管理者用
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    patch "/customers/:id/" => "customers#withdrawal", as: "withdrawal"
    resources :customers, only: [:show, :index, :update]
    resources :posts, only: [:show, :destroy]

  end


end

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <!-- ナビゲーションバー -->
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <!-- ロゴ -->
      <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
      <% if customer_signed_in? %>
      <span class="welcome-customer text-secondary">ようこそ<%= current_customer.name %>さん！</span>
      <% end %>
      <!-- ハンバーガーメニュー -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
        <li class="nav-item">
          <%= link_to "本棚を見る", books_path, class: 'nav-link text-success' %>
        </li>
        <li class="nav-item">
          <%= link_to "振り返りログ", customers_path, class: 'nav-link text-secondary' %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-danger' %>
        </li>
        <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-success' %>
        </li>
        <li class="nav-item">
          <%= link_to '管理者ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-danger' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-success' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-info' %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RackrackPf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <!--ヘッダー-->
    <%= render "layouts/header" %>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-light text-center text-lg-start">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020
        <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
        <a class="text-dark" href="https://developers.rakuten.com/" target="_blank">Supported by Rakuten Developers</a>
        <!-- Rakuten Web Services Attribution Snippet TO HERE -->
      </div>
    </footer>
  </body>
</html>